spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: sai
    password: sai
    url: jdbc:postgresql://localhost:5432/ocean?currentSchema=ocean


  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
